### ISSUE TITLE
Deploying EDC-CE with sovity-daps

### ISSUE THREAD

**Issue by skante93** [sovity/edc-ce#1131]
Hello,

I am trying to test the deployment of a local Sovity EDC-CE connector alongside a DAPS server but unsuccessfully so far, any help would be greatly appreciated. I should point out that I am not very familiar with keycloak.

### Docker Compose

Below is the <code>docker-compose.yml</code> file I used to deploy the setup (my starting point was the [local-demo-ce](https://github.com/sovity/edc-ce/tree/main/docs/deployment-guide/goals/local-demo-ce)):

<details>
   <summary>docker-compose.yml</summary>

```yaml
services:

  postgres:
    image: docker.io/library/postgres:16
    restart: always
    volumes:
      - ./my-postgres-init-db.sh:/docker-entrypoint-initdb.d/my-postgres-init-db.sh
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_LIST: daps,consumer_cp,consumer_dp,provider_connector
    healthcheck:
      test:
        - 'CMD-SHELL'
        - 'pg_isready -U postgres -d daps'
      interval: '1s'
      timeout: '5s'
      retries: 10

  daps:
    build: ./sovity-daps
    command: [ "start-dev", "--import-realm", "--health-enabled=true", "--metrics-enabled=true" ]
    restart: always
    depends_on: #["consumer-dp-db"]
      postgres:
        condition: 'service_healthy'
    volumes:
      - ./realm-export_v4.json:/opt/keycloak/data/import/daps.json
    healthcheck:
      test:
        - CMD-SHELL 
        - "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET / HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 && cat <&3"
      interval: 30s
      timeout: 5s
      retries: 20
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: daps
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HTTP_ENABLED: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: ****
      KC_BOOTSTRAP_ADMIN_PASSWORD: ****
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME: https://ws94-sov-pro-ctrl.tl.teralab-datascience.fr/
    ports:
      - 11004:8080

  consumer:
    image: 'nginx'
    restart: 'always'
    ports:
      - '22000:80'
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./nginx/entrypoint.sh:/entrypoint.sh
    entrypoint:
      - /entrypoint.sh
    environment:
      CONNECTOR_UPSTREAM_HOST: 'consumer-cp'
      CONNECTOR_PUBLIC_UPSTREAM_HOST: 'consumer-dp'
      FRONTEND_UPSTREAM_HOST: 'consumer-ui'

  consumer-ui:
    image: 'ghcr.io/sovity/edc-ce-ui:12.0.0'
    restart: 'always'
    environment:
      NEXT_PUBLIC_MANAGEMENT_API_URL: '/api/management'
      NEXT_PUBLIC_MANAGEMENT_API_KEY: 'SomeOtherApiKey'
  
  consumer-cp:
    image: 'ghcr.io/sovity/edc-ce:12.0.0'
    restart: 'always'
    depends_on: #["consumer-dp-db"]
      postgres:
        condition: 'service_healthy'
      daps:
        condition: 'service_healthy'
    environment:
      sovity.deployment.kind: 'control-plane-standalone'
      sovity.edc.fqdn.public: 'consumer'
      sovity.edc.fqdn.internal: 'consumer-cp'
      sovity.jdbc.url: 'jdbc:postgresql://postgres:5432/consumer_cp'
      sovity.jdbc.user: ${POSTGRES_USER}
      sovity.jdbc.password: ${POSTGRES_PASSWORD}
      sovity.management.api.iam.kind: 'management-iam-api-key'
      edc.api.auth.key: 'SomeOtherApiKey'
      sovity.edc.title: 'consumer Title'
      sovity.edc.description: 'consumer Description'
      sovity.edc.maintainer.name: 'consumer Maintainer'
      sovity.edc.maintainer.url: 'https://consumer/maintainer'
      sovity.edc.curator.name: 'consumer Curator'
      sovity.edc.curator.url: 'https://consumer/curator'
      sovity.edc.ui.preconfigured.counterparties: 'http://provider/api/dsp?participantId=provider'
      sovity.http.protocol: 'http://'
      sovity.print.config: 'true'
      sovity.logging.level: 'DEBUG'
      sovity.logging.kind: 'console'

      sovity.dataspace.kind: 'sovity-daps'
      edc.oauth.provider.jwks.url: https://ws94-sov-pro-ctrl.tl.teralab-datascience.fr/realms/DAPS/protocol/openid-connect/certs
      edc.oauth.token.url: https://ws94-sov-pro-ctrl.tl.teralab-datascience.fr/realms/DAPS/protocol/openid-connect/token
      edc.participant.id: consumer-cp

      sovity.vault.kind: vault-in-memory
      sovity.vault.in-memory.init.daps-cert: ${DAPS_CERT}
      sovity.vault.in-memory.init.daps-priv: ${DAPS_PRIV}

  consumer-dp:
    image: 'ghcr.io/sovity/edc-ce:12.0.0'
    restart: 'always'
    depends_on: #["consumer-dp-db"]
      postgres:
        condition: 'service_healthy'
      consumer-cp: 
        condition: 'service_started'
    environment:
      sovity.deployment.kind: 'data-plane-standalone'
      sovity.edc.fqdn.public: 'consumer'
      sovity.edc.fqdn.internal: 'consumer-dp'
      sovity.jdbc.url: 'jdbc:postgresql://postgres:5432/consumer_dp'
      sovity.jdbc.user: ${POSTGRES_USER}
      sovity.jdbc.password: ${POSTGRES_PASSWORD}
      sovity.management.api.iam.kind: 'management-iam-api-key'
      edc.api.auth.key: 'SomeOtherApiKey'
      sovity.http.protocol: 'http://'
      sovity.print.config: 'true'
      sovity.logging.level: 'DEBUG'
      sovity.logging.kind: 'console'

      sovity.internal.cp.fqdn: 'consumer-cp'
      sovity.internal.cp.protocol: 'http://'
      sovity.internal.cp.management.api.key: 'SomeOtherApiKey'

      sovity.dataspace.kind: 'sovity-daps'
      edc.oauth.provider.jwks.url: https://ws94-sov-pro-ctrl.tl.teralab-datascience.fr/realms/DAPS/protocol/openid-connect/certs
      edc.oauth.token.url: https://ws94-sov-pro-ctrl.tl.teralab-datascience.fr/realms/DAPS/protocol/openid-connect/token
      edc.participant.id: consumer-dp

      sovity.vault.kind: vault-in-memory
      sovity.vault.in-memory.init.daps-cert: ${DAPS_CERT}
      sovity.vault.in-memory.init.daps-priv: ${DAPS_PRIV}

  provider:
    image: 'nginx'
    restart: 'always'
    ports:
      - '11000:80'
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./nginx/entrypoint.sh:/entrypoint.sh
    entrypoint:
      - /entrypoint.sh
    environment:
      CONNECTOR_UPSTREAM_HOST: 'provider-connector'
      FRONTEND_UPSTREAM_HOST: 'provider-ui'

  provider-ui:
    image: 'ghcr.io/sovity/edc-ce-ui:12.0.0'
    restart: 'always'
    environment:
      NEXT_PUBLIC_MANAGEMENT_API_URL: '/api/management'
      NEXT_PUBLIC_MANAGEMENT_API_KEY: 'SomeOtherApiKey'
  provider-connector:
    image: 'ghcr.io/sovity/edc-ce:12.0.0'
    restart: 'always'
    depends_on: #["consumer-dp-db"]
      postgres:
        condition: 'service_healthy'
      daps: 
        condition: 'service_healthy'
    environment:
      sovity.deployment.kind: 'control-plane-with-integrated-data-plane'
      sovity.edc.fqdn.public: 'provider'
      sovity.edc.fqdn.internal: 'localhost'
      sovity.jdbc.url: 'jdbc:postgresql://postgres:5432/provider_connector'
      sovity.jdbc.user: ${POSTGRES_USER}
      sovity.jdbc.password: ${POSTGRES_PASSWORD}
      sovity.management.api.iam.kind: 'management-iam-api-key'
      edc.api.auth.key: 'SomeOtherApiKey'
      sovity.edc.title: 'provider Title'
      sovity.edc.description: 'provider Description'
      sovity.edc.maintainer.name: 'provider Maintainer'
      sovity.edc.maintainer.url: 'https://provider/maintainer'
      sovity.edc.curator.name: 'provider Curator'
      sovity.edc.curator.url: 'https://provider/curator'
      sovity.edc.ui.preconfigured.counterparties: 'http://consumer/api/dsp?participantId=consumer'
      sovity.http.protocol: 'http://'
      sovity.print.config: 'true'
      sovity.logging.level: 'DEBUG'
      sovity.logging.kind: 'console'

      sovity.dataspace.kind: 'sovity-daps'
      edc.oauth.provider.jwks.url: https://ws94-sov-pro-ctrl.tl.teralab-datascience.fr/realms/DAPS/protocol/openid-connect/certs
      edc.oauth.token.url: https://ws94-sov-pro-ctrl.tl.teralab-datascience.fr/realms/DAPS/protocol/openid-connect/token
      edc.participant.id: provider

      sovity.vault.kind: vault-in-memory
      sovity.vault.in-memory.init.daps-cert: ${DAPS_CERT}
      sovity.vault.in-memory.init.daps-priv: ${DAPS_PRIV}


volumes:
  postgres-data: {}
  
```
</details>

As you can see:
* I decided to split the consumer connector (separating the controlplane from the dataplane), but decided kept the provider connector whole.
* I specified the following configs in the hope it can allow me to use the <code>sovity-daps</code> in my connectors:

```yaml
      sovity.dataspace.kind: 'sovity-daps'
      edc.oauth.provider.jwks.url: https://ws94-sov-pro-ctrl.tl.teralab-datascience.fr/realms/DAPS/protocol/openid-connect/certs
      edc.oauth.token.url: https://ws94-sov-pro-ctrl.tl.teralab-datascience.fr/realms/DAPS/protocol/openid-connect/token
      edc.participant.id: provider

      sovity.vault.kind: vault-in-memory
      sovity.vault.in-memory.init.daps-cert: ${DAPS_CERT}
      sovity.vault.in-memory.init.daps-priv: ${DAPS_PRIV}
```

### Keycloak

After starting the docker compose services, I logged into keycloak and performed the following
* Created the <code>DAPS</code> realm
* I added three clients to that realm (matching the edc.participant.id, i.e. the OAuth client IDs): <code>provider</code>, <code>consumer-cp</code> and <code>consumer-dp</code>. Then for each of them:
  * In <code>Settings</code> tab: toggle on option <code>Client Authentication</code>, and check all the <code>Authentication Flows</code>
  * In <code>Keys</code> tab, import the ${DAPS_CERT} certificate (same as the one referred to in the docker-compose.yml)
  * In <code>Credentials</code> tab: change  <code>Client Authenticator</code> to "Signed Jwt" and <code>Signature algorithm</code> to "Any algorithm"
* List all client scopes and set their columns <code>Assigned types</code> to "None". Afterwards, add a new client scope named <code>idsc:IDS_CONNECTOR_ATTRIBUTES_ALL</code> and set its <code>Assigned type</code> to "Optional".

## The problem

When I try to request the catalog of the consumer from the provider (or vice-versa), I get following error : 
<details>
   <summary>Docker services Logs</summary>

```
provider-1            | 10.32.0.156 - schneider [23/Apr/2025:14:59:28 +0000] "GET /api/management/wrapper/ui/config HTTP/1.1" 200 145 "htt
ps://ws94-sov-pro-ui.tl.teralab-datascience.fr/catalog" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131
.0.0.0 Safari/537.36" "192.44.77.246"
provider-1            | 10.32.0.156 - schneider [23/Apr/2025:14:59:28 +0000] "GET /catalog/consumer/http%3A%2F%2Fconsumer%2Fapi%2Fdsp?_rsc
=1j273 HTTP/1.1" 200 979 "https://ws94-sov-pro-ui.tl.teralab-datascience.fr/catalog" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (
KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "192.44.77.246"
consumer-1            | 172.19.0.2 - - [23/Apr/2025:14:59:28 +0000] "POST /api/dsp/catalog/request HTTP/1.1" 401 327 "-" "okhttp/4.12.0" "
-"            
provider-connector-1  | 2025-04-23 14:59:28,878 [ERROR] Log4jMonitor - JerseyExtension: Unexpected exception caught
provider-connector-1  | org.eclipse.edc.spi.EdcException: {"@type":"dspace:CatalogError","dspace:code":"401","dspace:reason":"Unauthorized
","@context":{"@vocab":"https://w3id.org/edc/v0.0.1/ns/","edc":"https://w3id.org/edc/v0.0.1/ns/","dcat":"http://www.w3.org/ns/dcat#","dct"
:"http://purl.org/dc/terms/","odrl":"http://www.w3.org/ns/odrl/2/","dspace":"https://w3id.org/dspace/v0.8/"}}
provider-connector-1  |         at org.eclipse.edc.transaction.local.LocalTransactionContext.execute(LocalTransactionContext.java:81) ~[app.jar:?]
provider-connector-1  |         at de.sovity.edc.ce.modules.db.DslContextFactory.transactionResult(DslContextFactory.kt:46) ~[app.jar:?]
provider-connector-1  |         at de.sovity.edc.ce.api.ui.UiResourceImpl.getCatalogPageDataOffers(UiResourceImpl.kt:166) ~[app.jar:?]
provider-connector-1  |         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
provider-connector-1  |         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
provider-connector-1  |         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
provider-connector-1  |         at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
provider-connector-1  |         at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[app.jar:?]
provider-connector-1  |         at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146) ~[app.jar:?]
provider-connector-1  |         at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189) ~[app.jar:?]
provider-connector-1  |         at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[app.jar:?]
provider-connector-1  |         at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93) ~[app.jar:?]
provider-connector-1  |         at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[app.jar:?]
provider-connector-1  |         at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[app.jar:?]           
provider-connector-1  |         at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[app.jar:?]            
provider-connector-1  |         at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:274) [app.jar:?]
provider-connector-1  |         at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [app.jar:?]
provider-connector-1  |         at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [app.jar:?]
provider-connector-1  |         at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [app.jar:?]
provider-connector-1  |         at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [app.jar:?]
provider-connector-1  |         at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [app.jar:?]
provider-connector-1  |         at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:266) [app.jar:?]
provider-connector-1  |         at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:253) [app.jar:?]
provider-connector-1  |         at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:696) [app.jar:?]
provider-connector-1  |         at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) [app.jar:?]
provider-connector-1  |         at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) [app.jar:?]
provider-connector-1  |         at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358) [app.jar:?]
provider-connector-1  |         at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:312) [app.jar:?]
provider-connector-1  |         at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192) [app.jar:?]      
provider-connector-1  |         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.server.Server.handle(Server.java:563) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199) [app.jar:?] 
provider-connector-1  |         at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411) [app.jar:?] 
provider-connector-1  |         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194) [app.jar:?]
provider-connector-1  |         at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149) [app.jar:?]
provider-connector-1  |         at java.lang.Thread.run(Unknown Source) [?:?]
provider-connector-1  | Caused by: de.sovity.edc.ce.libs.mappers.dsp.DspCatalogServiceException: {"@type":"dspace:CatalogError","dspace:code":"401","dspace:reason":"Unauthorized","@context":{"@vocab":"https://w3id.org/edc/v0.0.1/ns/","edc":"https://w3id.org/edc/v0.0.1/ns/","dcat":"http://www.w3.org/ns/dcat#","dct":"http://purl.org/dc/terms/","odrl":"http://www.w3.org/ns/odrl/2/","dspace":"https://w3id.org/dspace/v0.8/"}}    
```
</details>

This seems to imply that the provider-connector managed to get a token from DAPS but was not recognized as valid by the consumer connector.

Can you point me to the right direction?

Thanks in advance.
